name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Deploy to AWS Lightsail
        env:
          LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
          LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
          ssh-keyscan -H $LIGHTSAIL_HOST >> ~/.ssh/known_hosts
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > lightsail_key.pem
          chmod 600 lightsail_key.pem
          scp -i lightsail_key.pem target/*.war ubuntu@$LIGHTSAIL_HOST:/home/ubuntu/tomcat/apache-tomcat-10.1.24/webapps/
